### Graph

In [1]:
import findspark
findspark.init()
from pyspark import SparkContext
sc =SparkContext()
from pyspark.sql import SparkSession
from pyspark.ml.feature import Tokenizer, RegexTokenizer
from pyspark.sql.functions import col, udf, lit
from pyspark.sql.types import IntegerType
from pyspark import SQLContext
from pyspark.ml.feature import StopWordsRemover
from pyspark.ml.feature import HashingTF, IDF
from pyspark.ml.feature import Normalizer
from pyspark.sql import SparkSession

sqlContext = SQLContext(sc)
spark = SparkSession \
    .builder \
    .appName("graph") \
    .getOrCreate()

In [2]:
# dataframe1 = sqlContext.read.json('hdfs://localhost:1234/user/tl2861/hw3/train.json')
df3 = sqlContext.read.json('../../data/AA/wiki_*')
df3 = df3.sample(False, 0.3, 42)
df3.printSchema()

root
 |-- id: string (nullable = true)
 |-- text: string (nullable = true)
 |-- title: string (nullable = true)
 |-- url: string (nullable = true)



In [3]:
# df3.createOrReplaceTempView("wikinews")
# sqlDF3 = spark.sql("select count(*) from wikinews")
# sqlDF3.show()

In [4]:
regexTokenizer = RegexTokenizer(inputCol="text", outputCol="words", pattern="[^A-Za-z]+", toLowercase=True)
tokenizedData = regexTokenizer.transform(df3)
stopWordsRemover = StopWordsRemover(inputCol="words", outputCol="filtered_words")
filteredData = stopWordsRemover.transform(tokenizedData)
hashingTF = HashingTF(inputCol="filtered_words", outputCol="raw_features", numFeatures=20)
featurizedData = hashingTF.transform(filteredData)
idf= IDF(inputCol="raw_features", outputCol="features")
idfModel = idf.fit(featurizedData)
data1 = idfModel.transform(featurizedData)
normalizer = Normalizer(inputCol="features", outputCol="norm")
data = normalizer.transform(data1)
data = data.sample(False, 0.2, 0)

In [5]:
# data1.show()
data.count()

1303

In [6]:
import numpy as np
feature = np.array(data.select('norm').collect())
# delete the 1 size axis
feature = np.squeeze(feature)
print(feature)

[[0.         0.08541561 0.19625114 ... 0.47727619 0.06370498 0.04417505]
 [0.24487209 0.22203587 0.16324806 ... 0.31902895 0.39743903 0.32152958]
 [0.39469053 0.40082848 0.18418891 ... 0.22854146 0.02135338 0.17768532]
 ...
 [0.32347965 0.16245009 0.1492983  ... 0.10806204 0.26251142 0.30805705]
 [0.08737911 0.28522918 0.34951643 ... 0.26562882 0.07091022 0.14751416]
 [0.32334694 0.07036616 0.06466939 ... 0.11233842 0.1836826  0.25474264]]


In [7]:
print(feature)

[[0.         0.08541561 0.19625114 ... 0.47727619 0.06370498 0.04417505]
 [0.24487209 0.22203587 0.16324806 ... 0.31902895 0.39743903 0.32152958]
 [0.39469053 0.40082848 0.18418891 ... 0.22854146 0.02135338 0.17768532]
 ...
 [0.32347965 0.16245009 0.1492983  ... 0.10806204 0.26251142 0.30805705]
 [0.08737911 0.28522918 0.34951643 ... 0.26562882 0.07091022 0.14751416]
 [0.32334694 0.07036616 0.06466939 ... 0.11233842 0.1836826  0.25474264]]


In [8]:
similarity = np.dot(feature, feature.T)

In [9]:
print(similarity)

[[1.         0.61512723 0.57363609 ... 0.61035521 0.55019456 0.71634007]
 [0.61512723 1.         0.81351014 ... 0.90934705 0.75781345 0.7723351 ]
 [0.57363609 0.81351014 1.         ... 0.7763073  0.72313427 0.69482769]
 ...
 [0.61035521 0.90934705 0.7763073  ... 1.         0.75225772 0.87379146]
 [0.55019456 0.75781345 0.72313427 ... 0.75225772 1.         0.69754186]
 [0.71634007 0.7723351  0.69482769 ... 0.87379146 0.69754186 1.        ]]


In [10]:
import pandas as pd
df_simi = pd.DataFrame(similarity[:,:])
display(df_simi)

0         1         2         3         4         5         6     \
0     1.000000  0.615127  0.573636  0.719247  0.617574  0.721159  0.653327   
1     0.615127  1.000000  0.813510  0.849005  0.856357  0.626851  0.917166   
2     0.573636  0.813510  1.000000  0.660083  0.820069  0.704701  0.901300   
3     0.719247  0.849005  0.660083  1.000000  0.837863  0.698090  0.815951   
4     0.617574  0.856357  0.820069  0.837863  1.000000  0.701870  0.883835   
5     0.721159  0.626851  0.704701  0.698090  0.701870  1.000000  0.759245   
6     0.653327  0.917166  0.901300  0.815951  0.883835  0.759245  1.000000   
7     0.594321  0.796633  0.817336  0.751154  0.786721  0.666855  0.867920   
8     0.605583  0.814672  0.780569  0.794879  0.757601  0.547077  0.840859   
9     0.624361  0.865663  0.750711  0.839105  0.828855  0.728618  0.909863   
10    0.629567  0.829800  0.770772  0.752041  0.769993  0.490260  0.798141   
11    0.621691  0.885656  0.740755  0.842327  0.897606  0.682104  0.878524   
12    0.627472  0.872001  0.815498  0.761943  0.811304  0.730245  0.915011   
13    0.700186  0.882615  0.779574  0.822171  0.865294  0.754468  0.890749   
14    0.618106  0.792389  0.826010  0.769335  0.719098  0.698436  0.885776   
15    0.587490  0.892397  0.824759  0.764321  0.790436  0.656344  0.913455   
16    0.537380  0.829220  0.806015  0.686038  0.764133  0.561376  0.856718   
17    0.731065  0.725907  0.757839  0.768206  0.741209  0.787265  0.829134   
18    0.700990  0.899961  0.845864  0.890991  0.904593  0.733150  0.942333   
19    0.588674  0.793951  0.927113  0.685367  0.771037  0.615692  0.855034   
20    0.600632  0.791250  0.801841  0.707986  0.817603  0.710316  0.810369   
21    0.577874  0.800470  0.818824  0.735795  0.838935  0.601371  0.867659   
22    0.634267  0.847644  0.815051  0.730535  0.757829  0.705852  0.850062   
23    0.662038  0.835989  0.778798  0.834700  0.808109  0.713991  0.885279   
24    0.665696  0.864150  0.669761  0.801485  0.812065  0.526611  0.795889   
25    0.525076  0.785042  0.567197  0.756950  0.793797  0.465674  0.749354   
26    0.625364  0.770596  0.713863  0.799257  0.713523  0.622246  0.840609   
27    0.642568  0.878897  0.759776  0.814885  0.829295  0.638366  0.899549   
28    0.585719  0.868587  0.658623  0.907621  0.836779  0.667513  0.805670   
29    0.809451  0.860433  0.772173  0.818745  0.785250  0.779324  0.854756   
...        ...       ...       ...       ...       ...       ...       ...   
1273  0.642154  0.762833  0.750916  0.654917  0.797445  0.690199  0.822750   
1274  0.568835  0.841495  0.817641  0.703843  0.842132  0.522548  0.841724   
1275  0.653903  0.857881  0.897626  0.757264  0.841911  0.711180  0.925955   
1276  0.486863  0.696151  0.779131  0.726303  0.855102  0.529826  0.746086   
1277  0.745624  0.784911  0.790087  0.818623  0.758253  0.759866  0.848483   
1278  0.654708  0.856940  0.765901  0.873091  0.901864  0.605389  0.879183   
1279  0.658106  0.875300  0.709963  0.919896  0.850917  0.616997  0.839190   
1280  0.607333  0.841407  0.773762  0.790677  0.772853  0.768194  0.882079   
1281  0.507133  0.849290  0.767540  0.787059  0.778065  0.533025  0.807378   
1282  0.571036  0.865945  0.834726  0.724825  0.817848  0.607641  0.913428   
1283  0.584795  0.833727  0.785672  0.771693  0.763161  0.690226  0.836833   
1284  0.637072  0.837551  0.825146  0.870459  0.860333  0.741524  0.882005   
1285  0.609171  0.791403  0.773159  0.823087  0.761099  0.652699  0.899809   
1286  0.688063  0.790029  0.763421  0.746114  0.722458  0.708164  0.795130   
1287  0.562034  0.829464  0.892470  0.689188  0.837747  0.737161  0.928420   
1288  0.673464  0.876366  0.796284  0.779764  0.878247  0.675452  0.931753   
1289  0.662341  0.905944  0.868476  0.844518  0.885845  0.766103  0.937489   
1290  0.566710  0.903609  0.843932  0.784617  0.800949  0.718335  0.903740   
1291  0.679024  0.803321  0.749682  0.848481  0.812466  0.667075  0.874367   
1292  0.644024  0.902558  0.8548

In [11]:
node = df3.select("title","url").toPandas()
node.insert(0,"id",node.index)
display(node)
# save node
node.to_csv("node.csv", sep=",",index = False, encoding="utf-8")

id                                              title  \
0        0                           Test article for dev use   
1        1                  Another test article for the devs   
2        2  Copenhagen hotel explosion may have been terro...   
3        3  Nokia appoints Microsoft Business Division Hea...   
4        4               Six die in US-Iraqi raid in Fallujah   
5        5  Tulsa media erroneously reports San Diego Comi...   
6        6                                           Victoria   
7        7  Continental and United Airlines shareholders a...   
8        8  Collingwood and St. Kilda draw 2010 AFL Grand ...   
9        9  Leonard Skinner, namesake of rock group Lynyrd...   
10      10  Greenpeace demands Chilean President create ma...   
11      11  Belgian Eurovision singer Fud Leclerc dies at ...   
12      12  Former Ecuadorian football referee Byron Moren...   
13      13  Evanston, Illinois middle school evacuated aft...   
14      14     Research in Motion to launch new tablet device   
15      15  Kenyan court jails seven pirates for 2009 atte...   
16      16  Owner of Segway Jimi Heselden dies after scoot...   
17      17  Genetic link to migraines discovered by resear...   
18      18  Utah police investigate polygamist family from...   
19      19  White House Chief of Staff Rahm Emanuel steps ...   
20      20        Collingwood win 2010 AFL Grand Final replay   
21      21  Plane crash on Catalina Island injures three, ...   
22      22             Plane crash in the Bahamas kills eight   
23      23                  Macaque kills newborn in Malaysia   
24      24           Australian Dollar reaches a 27 year high   
25      25  Patient in Buckinghamshire hospital was treate...   
26      26  Winning British EuroMillions lottery ticket wo...   
27      27  Chilean miners rescue to begin on Tuesday, Min...   
28      28  Additional damage to reservoir prompts evacuat...   
29      29  Baghdad judge clears pair of murdering six for...   
...    ...                                                ...   
6425  6425  FIFA World Cup 2018 day three: France, Denmark...   
6426  6426  FIFA World Cup 2018 day four: Mexico beats Ger...   
6427  6427  India: Mehbooba Mufti resigns as Jammu Kashmir...   
6428  6428    India: Maharashtra plastic ban comes into force   
6429  6429  Serbian Football Association complain about Sw...   
6430  6430      Dutch senate votes in favour of face veil ban   
6431  6431  India: Kerala police registers case against bi...   
6432  6432  Argentine footballer Mascherano announces inte...   
6433  6433  In Pictures: Helsinki Pride 2018 ends after re...   
6434  6434  French football: Gianluigi Buffon signs one-ye...   
6435  6435  FIFA World Cup 2018 quarterfinals: England bea...   
6436  6436   Swiss footballer Xherdan Shaqiri joins Liverpool   
6437  6437  English football: Chelsea announces Maurizio S...   
6438  6438  FIFA World Cup 2018: Belgium beats England 2-0...   
6439  6439  Indian Supreme Court: unconstitutional to bar ...   
6440  6440  Hindi poet and songwriter Gopal Das Neeraj die...   
6441  6441      Cretaceous baby snake fossil found in Myanmar   
6442  6442  Ecuador planning to end asylum for Wikileaks f...   
6443  6443  German footballer Mesut Özil announces retirem...   
6444  6444  Palestine elected as G-77's presiding country,...   
6445  6445  40th Berlin Christopher Street Day celebration...   
6446  6446  French footballer Lucas Digne joins Everton FC...   
6447  6447  FC Barcelona signs Chilean footballer Arturo V...   
6448  6448  Brazilian footballer Gabriel Jesus signs contr...   
6449  6449  Fossil genome shows hybrid of two extinct spec...   
6450  6450            Russians protest against pension reform   
6451  6451  CAR gets $6.3m emergency funding for children'...   
6452  6452  Study suggests Mars hosted life-sustaining hab...   
6453  6453  Man arrested on suspicion of molestation of si...   
6454  6454  A hacker threatened to delete M

In [12]:
edge = df_simi.stack().reset_index()
edge.columns = ['src','dst','similarity']
display(edge)
edge = edge.loc[edge['similarity'] > 0.95]
edge = edge.loc[edge['src'] != edge['dst']]
display(edge)
edge.to_csv("edge.csv",sep = ",", index = False, encoding = "utf-8")

src   dst  similarity
0           0     0    1.000000
1           0     1    0.615127
2           0     2    0.573636
3           0     3    0.719247
4           0     4    0.617574
5           0     5    0.721159
6           0     6    0.653327
7           0     7    0.594321
8           0     8    0.605583
9           0     9    0.624361
10          0    10    0.629567
11          0    11    0.621691
12          0    12    0.627472
13          0    13    0.700186
14          0    14    0.618106
15          0    15    0.587490
16          0    16    0.537380
17          0    17    0.731065
18          0    18    0.700990
19          0    19    0.588674
20          0    20    0.600632
21          0    21    0.577874
22          0    22    0.634267
23          0    23    0.662038
24          0    24    0.665696
25          0    25    0.525076
26          0    26    0.625364
27          0    27    0.642568
28          0    28    0.585719
29          0    29    0.809451
...       ...   ...         ...
1697779  1302  1273    0.795126
1697780  1302  1274    0.732741
1697781  1302  1275    0.794449
1697782  1302  1276    0.535856
1697783  1302  1277    0.756055
1697784  1302  1278    0.767231
1697785  1302  1279    0.733457
1697786  1302  1280    0.816393
1697787  1302  1281    0.677870
1697788  1302  1282    0.802336
1697789  1302  1283    0.801442
1697790  1302  1284    0.788927
1697791  1302  1285    0.816066
1697792  1302  1286    0.799867
1697793  1302  1287    0.752831
1697794  1302  1288    0.759538
1697795  1302  1289    0.754495
1697796  1302  1290    0.778606
1697797  1302  1291    0.766304
1697798  1302  1292    0.767428
1697799  1302  1293    0.757058
1697800  1302  1294    0.848371
1697801  1302  1295    0.773671
1697802  1302  1296    0.709755
1697803  1302  1297    0.799007
1697804  1302  1298    0.857411
1697805  1302  1299    0.812800
1697806  1302  1300    0.873791
1697807  1302  1301    0.697542
1697808  1302  1302    1.000000

[1697809 rows x 3 columns]

src   dst  similarity
1583        1   280    0.956902
2300        1   997    0.956527
2539        1  1236    0.956746
7875        6    57    0.962319
7900        6    82    0.966172
7949        6   131    0.960576
8077        6   259    0.957848
8098        6   280    0.966492
8157        6   339    0.956047
8163        6   345    0.956438
8168        6   350    0.968605
8281        6   463    0.958597
8324        6   506    0.950676
8355        6   537    0.969483
8359        6   541    0.967031
8402        6   584    0.966651
8405        6   587    0.980852
8464        6   646    0.965645
8551        6   733    0.964927
8553        6   735    0.956441
8580        6   762    0.968497
8592        6   774    0.950630
8610        6   792    0.970176
8690        6   872    0.950608
8762        6   944    0.978002
8972        6  1154    0.962995
9004        6  1186    0.961275
9011        6  1193    0.961437
9051        6  1233    0.953343
9054        6  1236    0.966881
...       ...   ...         ...
1680154  1289   587    0.952049
1680155  1289   588    0.961939
1680298  1289   731    0.959793
1680465  1289   898    0.954063
1680492  1289   925    0.954348
1680568  1289  1001    0.950383
1680614  1289  1047    0.954870
1680684  1289  1117    0.952037
1680808  1289  1241    0.962007
1684040  1292   564    0.953983
1684541  1292  1065    0.952409
1684747  1292  1271    0.952434
1686127  1294    45    0.957776
1687735  1295   350    0.955014
1689014  1296   326    0.951671
1691812  1298   518    0.956829
1691818  1298   524    0.962894
1692670  1299    73    0.953107
1692798  1299   201    0.953838
1692877  1299   280    0.958245
1693001  1299   404    0.953933
1693095  1299   498    0.951428
1693222  1299   625    0.951446
1693594  1299   997    0.970567
1693704  1299  1107    0.961259
1693707  1299  1110    0.951869
1693728  1299  1131    0.956210
1693795  1299  1198    0.958676
1693833  1299  1236    0.965656
1694509  1300   609    0.954500

[2496 rows x 3 columns]